"""
main.py
-------
Entry point for the AI Legal Question Answering System.

Run with:
    python main.py

Workflow per session:
    1. User uploads a document (PDF / DOCX / TXT).
    2. System extracts text (OCR if scanned).
    3. Language of the document is detected.
    4. Document text is translated to English if Tamil / Hindi.
    5. Text is cleaned (preprocessing).
    6. Document is chunked using structure-aware splitter.
    7. Embeddings are generated and stored in FAISS.
    8. Interactive Q&A loop begins:
         a. User types a question (English / Tamil / Hindi).
         b. Language detected; question translated to English.
         c. Relevant chunks retrieved via FAISS similarity search.
         d. Answer generated by RAG engine.
         e. Answer verified against retrieved context.
         f. Verified answer (or NOT_FOUND) + citation printed.
         g. Answer translated back to user's original language.
    9. User can ask another question or type 'exit' to quit.

No database. No web UI. Pure Python terminal application.
"""

import sys
import io
import logging
from pathlib import Path

# Force UTF-8 output and input on Windows terminals (fixes Unicode errors)
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")
    sys.stdin  = io.TextIOWrapper(sys.stdin.buffer, encoding="utf-8", errors="replace")

# ── Ensure the project root is on sys.path ──────────────────────────────────
_PROJECT_ROOT = Path(__file__).parent.resolve()
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import config
from utils import (
    setup_logging,
    validate_file,
    get_file_size_mb,
    cprint,
    print_separator,
    print_section_header,
    prompt_user,
    confirm,
    Timer,
)
from ocr          import OCRProcessor
from translator   import Translator
from preprocessor import TextPreprocessor
from chunker      import StructureAwareChunker
from embeddings   import EmbeddingModel
from retriever    import VectorRetriever
from rag_engine   import RAGEngine
from verification import AnswerVerifier

logger = setup_logging("main")


# ─────────────────────────────────────────────
# BANNER
# ─────────────────────────────────────────────

_BANNER = """
+======================================================================+
|                                                                      |
|     AI Legal & Government Document Question Answering System         |
|                                                                      |
|     Research Prototype  |  Tamil Nadu Government  |  Python 3.12+   |
|                                                                      |
|     Supported Languages : English  |  Tamil  |  Hindi               |
|     Supported Formats   : PDF  |  Scanned PDF  |  DOCX  |  TXT     |
|                                                                      |
|  [!] Answers are sourced ONLY from uploaded documents.               |
|      The system NEVER uses its own knowledge.                        |
|                                                                      |
+======================================================================+
"""


def print_banner() -> None:
    cprint(_BANNER, colour="cyan", bold=True)


# ─────────────────────────────────────────────
# OUTPUT FORMATTER
# ─────────────────────────────────────────────

def print_qa_result(
    original_question: str,
    detected_lang:     str,
    translated_question: str,
    retrieved_sections: list,
    answer_en:          str,
    answer_native:      str,
    verification,
) -> None:
    """
    Print the full QA result in the prescribed output format.
    """
    lang_name = config.SUPPORTED_LANGUAGES.get(detected_lang, detected_lang)

    print_separator("═", 70, "cyan")
    cprint("  QUESTION & ANSWER RESULT", colour="cyan", bold=True)
    print_separator("═", 70, "cyan")

    # Question metadata
    cprint(f"\n  Question         : {original_question}", colour="white", bold=True)
    cprint(f"  Detected Language: {lang_name} ({detected_lang})", colour="yellow")
    if detected_lang != "en":
        cprint(f"  Translated Q     : {translated_question}", colour="yellow")

    # Retrieved sections
    print_separator("─", 70)
    cprint("  Retrieved Sections:", colour="blue", bold=True)
    for r in retrieved_sections:
        label = r.chunk.section_label or f"Chunk {r.chunk.chunk_id}"
        pages = ", ".join(str(p) for p in r.chunk.page_numbers) or "N/A"
        cprint(
            f"    [{r.rank}] {label}  |  Page(s): {pages}  |  Score: {r.score_percent:.1f}%",
            colour="blue",
        )

    # Answer
    print_separator("─", 70)
    cprint("  Generated Answer:", colour="green", bold=True)

    def _print_answer_lines(text: str, colour: str, bold: bool = False, prefix: str = "  ") -> None:
        """Print each line of an answer on its own line for readability."""
        lines = [ln.strip() for ln in text.strip().splitlines() if ln.strip()]
        if not lines:
            cprint(f"{prefix}{text}", colour=colour, bold=bold)
            return
        for line in lines:
            cprint(f"{prefix}{line}", colour=colour, bold=bold)

    if detected_lang != "en":
        cprint(f"\n  [English Answer]:", colour="white", bold=True)
        _print_answer_lines(answer_en, colour="white")
        cprint(f"\n  [{lang_name} Answer]:", colour="green", bold=True)
        _print_answer_lines(answer_native, colour="green", bold=True)
    else:
        print()
        _print_answer_lines(answer_native, colour="green", bold=True)

    # Verification
    print_separator("─", 70)
    v_colour = "green" if verification.passed else "red"
    cprint(
        f"  Verification     : {verification.status_label}",
        colour=v_colour,
        bold=True,
    )
    if not verification.passed and verification.failure_reason:
        cprint(f"  Failure Reason   : {verification.failure_reason}", colour="red")

    # Confidence & Citation
    if verification.passed and verification.confidence > 0:
        cprint(
            f"  Confidence Score : {verification.confidence_str}",
            colour="green",
        )
        cprint(
            f"  Source Citation  : {verification.citation.format()}",
            colour="yellow",
        )

    print_separator("═", 70, "cyan")
    print()


# ─────────────────────────────────────────────
# DOCUMENT LOADING PIPELINE
# ─────────────────────────────────────────────

class DocumentSession:
    """
    Encapsulates a single-document QA session.

    Attributes:
        file_path:   Path to the uploaded document.
        chunks:      List of DocumentChunk objects.
        retriever:   Populated VectorRetriever.
        doc_lang:    Detected document language.
    """

    def __init__(self) -> None:
        self.file_path  = None
        self.chunks     = []
        self.retriever  = None
        self.doc_lang   = "en"
        self.total_pages = 1

        # Shared component instances
        self._ocr         = OCRProcessor()
        self._translator  = Translator()
        self._preprocessor = TextPreprocessor()
        self._chunker     = StructureAwareChunker()
        self._embed_model = EmbeddingModel()
        self._rag         = RAGEngine()
        self._verifier    = AnswerVerifier()

    def load(self, file_path_str: str) -> None:
        """
        Full document loading pipeline:
        OCR → Language Detection → Translation → Preprocessing → Chunking → Indexing.

        Args:
            file_path_str: Path string provided by the user.
        """
        # ── Step 0: Validate file ────────────────────────────────────────────
        print_section_header("STEP 1 — Loading Document")
        file_path = validate_file(file_path_str)
        self.file_path = file_path
        size_mb = get_file_size_mb(file_path)
        cprint(f"  File : {file_path.name}", colour="white")
        cprint(f"  Size : {size_mb:.2f} MB", colour="white")

        # ── Step 1: OCR ──────────────────────────────────────────────────────
        cprint("\n  Extracting text (OCR if needed)…", colour="yellow")
        ocr_result = self._ocr.process(file_path)
        self.total_pages = ocr_result.total_pages
        cprint(
            f"  Extracted {ocr_result.total_pages} page(s). "
            f"OCR used: {ocr_result.used_ocr}",
            colour="green",
        )

        raw_text = ocr_result.raw_text
        if not raw_text.strip():
            raise ValueError("No text could be extracted from the document.")

        # ── Step 2: Language Detection ───────────────────────────────────────
        print_section_header("STEP 2 — Language Detection")
        self.doc_lang = self._translator.detect_language(raw_text)
        lang_name = config.SUPPORTED_LANGUAGES.get(self.doc_lang, "Unknown")
        cprint(
            f"  Document Language: {lang_name} ({self.doc_lang})",
            colour="cyan",
        )

        # ── Step 3: Translation (if not English) ─────────────────────────────
        if self.doc_lang != "en":
            print_section_header(f"STEP 3 — Translating {lang_name} → English")
            cprint(
                "  Translating document. This may take a few minutes for large files…",
                colour="yellow",
            )
            with Timer("Full document translation", logger):
                raw_text = self._translator.to_english(raw_text, self.doc_lang)
            cprint("  Translation complete.", colour="green")
        else:
            cprint("\n  Document is in English — translation skipped.", colour="dim")

        # ── Step 4: Preprocessing ────────────────────────────────────────────
        print_section_header("STEP 4 — Text Preprocessing")
        pre_result = self._preprocessor.clean(raw_text)
        cprint(
            f"  Cleaned {pre_result.original_length} → {pre_result.cleaned_length} chars "
            f"({pre_result.reduction_percent}% reduction).",
            colour="cyan",
        )
        if pre_result.go_numbers_found:
            cprint(
                f"  GO Numbers detected: {', '.join(pre_result.go_numbers_found)}",
                colour="yellow",
            )

        # ── Step 5: Chunking ─────────────────────────────────────────────────
        print_section_header("STEP 5 — Structure-Aware Chunking")
        self.chunks = self._chunker.chunk(
            pre_result.cleaned_text,
            pages=ocr_result.pages,
        )
        # Annotate chunks with GO numbers metadata
        for chunk in self.chunks:
            import re
            go_nums = re.findall(
                r"G\.O\.\s*(?:Ms\.|Rt\.|No\.?)?\s*\d+|GO\s*(?:No\.?)?\s*\d+",
                chunk.text,
                re.IGNORECASE,
            )
            chunk.metadata["go_numbers"] = go_nums

        cprint(f"  Created {len(self.chunks)} chunk(s).", colour="cyan")

        # ── Step 6: Embedding + Indexing ─────────────────────────────────────
        print_section_header("STEP 6 — Generating Embeddings & Indexing")
        cprint(
            "  Generating embeddings — first run downloads the model (~1-2 GB).",
            colour="yellow",
        )
        self.retriever = VectorRetriever(self._embed_model)
        self.retriever.index_chunks(self.chunks)
        cprint(
            f"  FAISS index built. {self.retriever.total_chunks} vectors in memory.",
            colour="green",
        )

        print_separator("═", 70, "green")
        cprint(
            "  ✓ Document ready for question answering!", colour="green", bold=True
        )
        print_separator("═", 70, "green")
        print()

    # ── Q&A ──────────────────────────────────────────────────────────────────

    def answer(self, question: str) -> None:
        """
        Process a user question end-to-end and print the result.

        Args:
            question: Raw question string in any supported language.
        """
        if not question.strip():
            cprint("  [!] Empty question — skipping.", colour="yellow")
            return

        # ── Detect question language ─────────────────────────────────────────
        question_lang = self._translator.detect_language(question)

        # ── Translate question to English ────────────────────────────────────
        question_en = self._translator.to_english(question, question_lang)
        logger.info(
            "Question | lang=%s | en=%r", question_lang, question_en[:100]
        )

        # ── Retrieve relevant chunks ─────────────────────────────────────────
        is_summary = any(w in question_en.lower() for w in ["summary", "summarise", "summarize"])
        if is_summary:
            results = self.retriever.retrieve(
                question_en,
                top_k=max(16, config.RETRIEVAL_TOP_K * 2),
                min_score=config.RETRIEVAL_MIN_SCORE * 0.5,
            )
        else:
            results = self.retriever.retrieve(question_en)
        if not results:
            cprint(
                "\n  No relevant sections found in the document.",
                colour="red",
            )
            self._print_not_found(question, question_lang)
            return

        # ── Generate answer (attempt 1) ──────────────────────────────────────
        answer_en = self._rag.generate(question_en, results, total_pages=self.total_pages)

        # ── Verify answer ────────────────────────────────────────────────────
        verification = self._verifier.verify(answer_en, results)

        # ── Retry if failed ──────────────────────────────────────────────────
        if not verification.passed:
            logger.info("Verification failed — retrying with wider retrieval.")
            results_wide = self.retriever.retrieve(
                question_en,
                top_k=config.RETRIEVAL_TOP_K + 3,
                min_score=config.RETRIEVAL_MIN_SCORE * 0.6,
            )
            answer_en_retry = self._rag.generate(question_en, results_wide, total_pages=self.total_pages)
            verification    = self._verifier.verify(answer_en_retry, results_wide)
            if verification.passed:
                answer_en = answer_en_retry
                results   = results_wide

        # ── Translate answer back to user's language ─────────────────────────
        answer_native = self._translator.from_english(
            verification.answer, question_lang
        )

        # ── Print result ─────────────────────────────────────────────────────
        print_qa_result(
            original_question   = question,
            detected_lang       = question_lang,
            translated_question = question_en,
            retrieved_sections  = results,
            answer_en           = verification.answer,
            answer_native       = answer_native,
            verification        = verification,
        )

    @staticmethod
    def _print_not_found(question: str, lang: str) -> None:
        """Print a minimal not-found result block."""
        lang_name = config.SUPPORTED_LANGUAGES.get(lang, lang)
        print_separator("═", 70, "red")
        cprint("  QUESTION & ANSWER RESULT", colour="red", bold=True)
        print_separator("═", 70, "red")
        cprint(f"\n  Question          : {question}", colour="white")
        cprint(f"  Detected Language : {lang_name}", colour="yellow")
        print_separator("─", 70)
        cprint(
            "  Generated Answer  : Information not found in the uploaded document.",
            colour="red",
            bold=True,
        )
        cprint("  Verification      : N/A (no matching context)", colour="red")
        print_separator("═", 70, "red")
        print()


# ─────────────────────────────────────────────
# INTERACTIVE LOOP
# ─────────────────────────────────────────────

def run_interactive(session: DocumentSession) -> None:
    """
    Main Q&A loop.
    Prompts the user for questions until they type 'exit' or 'quit'.
    """
    cprint(
        "  Type your question in English, Tamil, or Hindi.",
        colour="white",
    )
    cprint(
        "  Type 'exit' or 'quit' to end the session.",
        colour="dim",
    )
    print()

    while True:
        question = prompt_user("Your Question")
        if not question:
            continue
        if question.lower() in {"exit", "quit", "q", "bye"}:
            cprint("\n  Session ended. Goodbye!\n", colour="cyan")
            break
        session.answer(question)


# ─────────────────────────────────────────────
# MAIN ENTRY POINT
# ─────────────────────────────────────────────

def main() -> None:
    """
    Application entry point.

    Flow:
        1. Print banner.
        2. Prompt user for document path.
        3. Run document loading pipeline.
        4. Start interactive Q&A loop.
        5. Graceful shutdown on exit / Ctrl-C.
    """
    print_banner()

    session = DocumentSession()

    # ── Document upload ──────────────────────────────────────────────────────
    print_section_header("DOCUMENT UPLOAD")
    cprint(
        "  Supported: PDF, Scanned PDF, DOCX, TXT",
        colour="dim",
    )

    while True:
        path_str = prompt_user(
            "Enter the full path to your document (or 'exit' to quit)"
        )
        if path_str.lower() in {"exit", "quit"}:
            cprint("  Exiting. Goodbye!\n", colour="cyan")
            sys.exit(0)

        try:
            session.load(path_str)
            break
        except FileNotFoundError as exc:
            cprint(f"\n  [ERROR] {exc}", colour="red")
        except ValueError as exc:
            cprint(f"\n  [ERROR] {exc}", colour="red")
        except Exception as exc:
            logger.exception("Unexpected error during document loading.")
            cprint(f"\n  [ERROR] Unexpected error: {exc}", colour="red")
            cprint("  Please try a different document.", colour="yellow")

    # ── Q&A loop ─────────────────────────────────────────────────────────────
    try:
        run_interactive(session)
    except KeyboardInterrupt:
        cprint("\n\n  Interrupted by user. Goodbye!\n", colour="yellow")


if __name__ == "__main__":
    main()
